Land_of_Lakes/routes/add.py
from flask import Blueprint, render_template
from ..db_connector.db_connector import connect_to_database, execute_query
from ..forms import (ClientForm, AdvisorForm, OneAccountForm, TwoAccountForm,
                     UpdateClient, DeleteForm, HowManyAccountsForm, AskIfNull,
                     UpdateClientAddress)

add = Blueprint('add', __name__)


@add.route('/add_client', methods=['GET', 'POST'])
def add_client():
    """
    CREATE Route - Adds a Client to the database
    """

    db_connection = connect_to_database()

    form = ClientForm()
    submitted = False

    if form.validate_on_submit():

        ssn = form.ssn.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        city = form.city.data
        state = form.state.data
        house_number = form.house_number.data
        zip_code = form.zip_code.data
        email = form.email.data

        print('Info from Forms')
        print('---------------')
        print("ssn: " + str(ssn))
        print("first_name: " + str(first_name))
        print("last_name: " + str(last_name))
        print("city: " + str(city))
        print("state: " + str(state))
        print("house_number: " + str(house_number))
        print("zip_code: " + str(zip_code))
        print("email: " + str(email))

        # This will insert the form data into the addresses table
        address_query = (f"INSERT INTO `addresses` (`city`, `state`,\
                                `house_number`, `zip_code`)\
                           VALUES ('{city}', '{state}', '{house_number}',\
                                '{zip_code}');")

        execute_query(db_connection, address_query)

        # This will grab the most recent address_id added to the addresses
        get_address = "SELECT address_id FROM addresses ORDER BY address_id\
                       DESC LIMIT 1;"

        address_id = execute_query(db_connection, get_address).fetchall()
        address_id = address_id[0][0]
        print(address_id)

        # Insert into the client table
        client_query = (f"INSERT INTO `clients`(`ssn`, `first_name`,\
                            `last_name`, `email`, `address_id`)\
                        VALUES ('{ssn}', '{first_name}', '{last_name}',\
                            '{email}', '{address_id}');")

        execute_query(db_connection, client_query)

        submitted = True

    return render_template('add_client.html', form=form, submitted=submitted)


@add.route('/add_advisor', methods=['GET', 'POST'])
def add_advisor():
    """
    CREATE Route - Adds an advisor to the database
    """

    db_connection = connect_to_database()

    form = AdvisorForm()
    submitted = False

    if form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data
        area_of_expertise = form.expertise.data

        print('Info from Forms')
        print('---------------')
        print("first_name: " + str(first_name))
        print("last_name: " + str(last_name))
        print("area_of_expertise: " + str(area_of_expertise))

        advisor_query = (f"INSERT INTO `financial_advisors` (`first_name`,\
                            `last_name`, `area_of_expertise`)\
                          VALUES ('{first_name}', '{last_name}',\
                            '{area_of_expertise}');")

        print(advisor_query)

        execute_query(db_connection, advisor_query)

        submitted = True

    return render_template('add_advisor.html', form=form, submitted=submitted)


@add.route('/add_account', methods=['GET', 'POST'])
def add_account():
    """
    CREATE Route - Adds an account to the database
    """

    db_connection = connect_to_database()

    how_many_form = HowManyAccountsForm()
    one_form = OneAccountForm()
    two_form = TwoAccountForm()

    if how_many_form.validate_on_submit():
        num_wanted = how_many_form.number_wanted.data
        print("Client wants " + str(num_wanted) + " account owners")

        return render_template('add_account.html',
                               how_many_form=how_many_form,
                               num_wanted=num_wanted, one_form=one_form,
                               two_form=two_form)

    if one_form.validate_on_submit():
        client_id = one_form.id.data

        print('Info from Forms')
        print('---------------')
        print("client_id: " + str(client_id))

        # default balance to $0
        balance = 0

        # Add a new account for one, single client
        accounts_query = (f"INSERT INTO `accounts` (`balance`)\
                          VALUES ('{balance}');")

        execute_query(db_connection, accounts_query)

        get_account = "SELECT account_id FROM accounts ORDER BY account_id\
                       DESC LIMIT 1;"

        account_id = execute_query(db_connection, get_account).fetchall()
        account_id = account_id[0][0]
        print(account_id)

        # connect the account to the client

        connection_query = (f"INSERT INTO `clients_accounts` (`client_id`, `account_id`)\
                            VALUES ('{client_id}', '{account_id}');")

        execute_query(db_connection, connection_query)

    if two_form.validate_on_submit():
        id_one = two_form.id_one.data
        id_two = two_form.id_two.data

        print('Info from Forms')
        print('---------------')
        print("id_one: " + str(id_one))
        print("id_two: " + str(id_two))
        # default balance to $0
        balance = 0

        # Add a new account for one, single client
        accounts_query = (f"INSERT INTO `accounts` (`balance`)\
                          VALUES ('{balance}');")

        execute_query(db_connection, accounts_query)

        get_account = "SELECT account_id FROM accounts ORDER BY account_id\
                       DESC LIMIT 1;"

        account_id = execute_query(db_connection, get_account).fetchall()
        account_id = account_id[0][0]
        print(account_id)

        # connect the account to the client

        connection_query = (f"INSERT INTO `clients_accounts` (`client_id`, `account_id`)\
                            VALUES ('{id_one}', '{account_id}');")

        execute_query(db_connection, connection_query)

        connection_query = (f"INSERT INTO `clients_accounts` (`client_id`, `account_id`)\
                            VALUES ('{id_two}', '{account_id}');")

        execute_query(db_connection, connection_query)

    return render_template('add_account.html', how_many_form=how_many_form)


@add.route('/update_client', methods=['GET', 'POST'])
def update_client():
    """
    UPDATE Route - Updates a client to the database
    """
    db_connection = connect_to_database()

    make_null_form = AskIfNull()
    update_client_only_form = UpdateClient()
    update_client_address_form = UpdateClientAddress()
    msg = ""

    if make_null_form.validate_on_submit():
        make_null = make_null_form.make_null.data
        print(make_null)

        if make_null == 'True':

            return render_template('update_client.html',
                                   make_null_form=make_null_form,
                                   make_null=make_null,
                                   update_client_only_form # noqa
                                   =update_client_only_form)

        elif make_null == 'False':
            return render_template('update_client.html',
                                   make_null_form=make_null_form,
                                   make_null=make_null,
                                   update_client_address_form # noqa
                                   =update_client_address_form)

    if update_client_address_form.validate_on_submit():
        id = update_client_address_form.id.data
        ssn = update_client_address_form.ssn.data
        first_name = update_client_address_form.first_name.data
        last_name = update_client_address_form.last_name.data
        email = update_client_address_form.email.data
        city = update_client_address_form.city.data
        state = update_client_address_form.state.data
        house_number = update_client_address_form.house_number.data
        zip_code = update_client_address_form.zip_code.data

        get_address = f"SELECT address_id FROM clients WHERE client_id={id};"
        address_id = execute_query(db_connection, get_address).fetchall()
        print(address_id)

        address_id = address_id[0][0]

        # if, address doesn't exist, create a new address
        if address_id is None:

            # This will insert the form data into the addresses table
            address_query = (f"INSERT INTO `addresses` (`city`, `state`,\
                                    `house_number`, `zip_code`)\
                            VALUES ('{city}', '{state}', '{house_number}',\
                                    '{zip_code}');")

            execute_query(db_connection, address_query)

            # This will grab the most recent address_id added to the addresses
            get_address = "SELECT address_id FROM addresses ORDER BY address_id\
                        DESC LIMIT 1;"

            address_id = execute_query(db_connection, get_address).fetchall()
            address_id = address_id[0][0]
            print(address_id)

            client_query = (f"UPDATE `clients`\
                  SET\
                          `ssn` = {ssn},\
                          `first_name` = '{first_name}',\
                          `last_name` = '{last_name}',\
                          `email` = '{email}',\
                          `address_id` = '{address_id}'\
                  WHERE\
                          `client_id` = {id};")

            execute_query(db_connection, client_query)

        # else Address does exists, update address
        else:

            address_query = (f"UPDATE `addresses`\
                    SET\
                            `city` = '{city}',\

Land_of_Lakes/routes/main.py
from flask import Blueprint, render_template
from ..forms import TablesForm, ConnectAdvisorForm, SearchForm
from ..db_connector.db_connector import connect_to_database, execute_query

main = Blueprint('main', __name__)


# Homepage route
@main.route('/')
def index():

    return render_template('index.html')


# This route will connect an existing financial advisor to an existing client
@main.route('/connect_advisor', methods=['GET', 'POST'])
def connect_advisor():
    db_connection = connect_to_database()
    form = ConnectAdvisorForm()
    if form.validate_on_submit():
        client_id = form.client_id.data
        advisor_id = form.advisor_id.data
        clients_advisors_query = (f"INSERT INTO `clients_advisors`\
                                    (`client_id`, `advisor_id`)\
                                VALUES ('{client_id}', '{advisor_id}');")

        execute_query(db_connection, clients_advisors_query)

    return render_template('connect_advisor.html', form=form)


# This route will search the database for a client with the specified form data.
# If the string is found in the database, it will be rendered into the html page.
@main.route('/search_database', methods=['GET', 'POST'])
def search_database():
    db_connection = connect_to_database()
    form = SearchForm()

    if form.validate_on_submit():
        search_term = form.searched_parameter.data
        print("searching for: " + search_term)

        query = (f"SELECT * FROM `clients`\
                 WHERE last_name LIKE '{search_term}%';")

        rows = execute_query(db_connection, query, None).fetchall()

        return render_template('search_database.html', form=form, rows=rows)

    return render_template('search_database.html', form=form)

# This route will display data from each one of our tables. The user is provided a drop-
# down menu in which to choose the table data they wish to view. The resulting data from the
# cooresponding table is then rendered to the user.
@main.route('/view_tables', methods=['GET', 'POST'])
def view_tables():
    db_connection = connect_to_database()

    form = TablesForm()

    if form.validate_on_submit():
        # Display clients table data
        if form.tables.data == 'clients':
            query = ("SELECT\
                        `client_id` as 'Client ID',\
                        `ssn` as 'Social Security Number',\
                    CONCAT(`first_name`, ' ', `last_name`) as 'Client Name',\
                        `email` as 'Email',\
                        `address_id` as 'Address ID'\
                     FROM\
                        `clients`;")

            rows = execute_query(db_connection, query).fetchall()

            return render_template('view_clients.html', form=form, rows=rows)
        # Display accounts table data
        elif form.tables.data == 'accounts':
            query = ("SELECT\
                        `account_id` as 'Account Number',\
                        `balance` as 'Account Balance'\
                     FROM\
                        `accounts`;")

            rows = execute_query(db_connection, query).fetchall()

            return render_template('view_accounts.html', form=form, rows=rows)
        # Display clients_advisors table data
        elif form.tables.data == 'clients_advisors':
            query = ("SELECT\
                        `client_advisor_id` as 'Client Advisor ID',\
                        clients.client_id as 'Client ID',\
                        clients.first_name as 'C First',\
                        clients.last_name as 'C Last',\
                        financial_advisors.advisor_id as 'Advisor ID',\
                        financial_advisors.first_name as 'A First',\
                        financial_advisors.last_name as 'A Last'\
                    FROM\
                        `clients_advisors`\
                        INNER JOIN clients\
                        ON clients.client_id=clients_advisors.client_id\
                        INNER JOIN financial_advisors\
                        ON financial_advisors.advisor_id\
                           =clients_advisors.advisor_id;")

            rows = execute_query(db_connection, query).fetchall()

            return render_template('view_clients_advisors.html',
                                   form=form,
                                   rows=rows)

        # Display clients_accounts table data
        elif form.tables.data == 'clients_accounts':
            query = ("SELECT\
                            `client_account_id` as 'Client Account ID',\
                            clients.first_name as 'First Name',\
                            clients.last_name as 'Last Name',\
                            clients.client_id as 'Client ID',\
                            accounts.account_id as 'Account ID'\
                            FROM\
                            `clients_accounts`\
                            INNER JOIN clients\
                            ON clients.client_id=clients_accounts.client_id\
                            INNER JOIN accounts\
                            ON accounts.account_id\
                            =clients_accounts.account_id;")

            rows = execute_query(db_connection, query).fetchall()

            return render_template('view_clients_accounts.html',
                                   form=form,
                                   rows=rows)

        # Display addresses table data
        elif form.tables.data == 'addresses':
            query = ("SELECT\
                            `address_id` as 'Address ID',\
                            `city` as 'City',\
                            `state` as 'State',\
                            `house_number` as 'House Number',\
                            `zip_code` as 'Zip Code'\
                    FROM\
                            `addresses`;")

            rows = execute_query(db_connection, query).fetchall()

            return render_template('view_addresses.html', form=form, rows=rows)

        # Display financial_advisors table data
        elif form.tables.data == 'financial_advisors':

            query = ("SELECT\
                        `advisor_id` as 'Advisor ID',\
                        `area_of_expertise` as 'Area of Expertise',\
                        `first_name` as 'First Name',\
                        `last_name` as 'Last Name'\
                    FROM\
                        `financial_advisors`;")

            rows = execute_query(db_connection, query).fetchall()

            return render_template('view_financial_advisors.html', form=form, rows=rows)

    return render_template('view_tables.html', form=form)

Land_of_Lakes/templates/add_account.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1>Add an account for a Client</h1>
  <p>This form will add an account for the requested client(s) using their ID's. Don't know the client's ID? Look it up <a href="{{ url_for('main.search_database') }}">here!</a></p>
  <div class='form-group'>
    <form method="POST">
      {{ how_many_form.hidden_tag() }}
      {{ how_many_form.number_wanted.label }} {{how_many_form.number_wanted(class="btn btn-outline-info dropdown-toggle")}}
      {{ how_many_form.submit(class="btn btn-primary") }} 
    </form>
  </div>

  {% if num_wanted == "1" %}
  <div class='form-group'>
    <form method="POST">
      {{ one_form.hidden_tag() }}
      <div class="form-row">
        <div class="col-auto">
          {{ one_form.id.label }} {{one_form.id(class="form-control")}}
        </div>
      </div>
      <br></br>
        {{ one_form.submit(class="btn btn-primary") }} 
    </form>
  </div>
  {% elif num_wanted == "2" %}
  <div class='form-group'>
    <form method="POST">
      {{ two_form.hidden_tag() }}
      <div class="form-row">
        <div class="col-auto">
          {{ two_form.id_one.label }} {{two_form.id_one}}
        </div>
        <div class="col-auto">
          {{ two_form.id_two.label }} {{two_form.id_two}}
        </div>
      </div>
      <br></br>
      {{ two_form.submit(class="btn btn-primary") }} 
    </form>
  </div>
  {% endif %}

</div>

{% endblock %}

Land_of_Lakes/templates/add_advisor.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Add Financial Advisor</h1>

  <p>This form will an advisor to the database. By default, advisors do not
  have a book of clients</p>

  <div class='form-group'>
    <form method="POST">
      {{ form.hidden_tag() }}
      <div class='form-row'>
        <div class="col-auto">
          {{ form.first_name.label }} {{form.first_name}}
        </div>
        <div class="col-auto">
          {{ form.last_name.label }} {{form.last_name}}
        </div>
      </div>
      <div class='form-row'>
        <div class="col-auto">
          {{ form.expertise.label }} {{form.expertise(class="btn btn-outline-info dropdown-toggle")}}
        </div>
      </div>
      {{ form.submit(class="btn btn-primary") }} 
    </form>
  </div>
  {%if submitted %}
  <h3>Advisor Submitted!</h3>
  {% endif %}
</div>
{% endblock %}

Land_of_Lakes/templates/add_client.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Add Client</h1>

  <p>This Form will add a Client and their Address to the database. A client
  <em>must</em> have an address to start out with, but if you want to nullify
  the many to one relationship, you can do so when updating the client </p>

  <div class='form-group'>
    <form method="POST" action="{{ url_for('add.add_client') }}">
      {{ form.hidden_tag() }}
      <div class="form-row">
        <div class="col-auto">
          {{ form.ssn.label }} {{form.ssn(class="form-control", placeholder="Social Security Number")}} 
        </div>
        <div class="col-auto">
          {{ form.email.label }} {{form.email(class="form-control", placeholder="Email")}}
        </div>
      </div>
      <br></br>
      <div class="form-row">
        <div class="col-auto">
          {{ form.first_name.label }} {{form.first_name(class="form-control", placeholder="First Name")}} 
        </div>
        <div class="col-auto">
          {{ form.last_name.label }} {{form.last_name(class="form-control", placeholder="Last Name")}} 
        </div>
      </div>
      <br></br>
      <div class="form-row">
        <div class="col-auto">
          {{ form.house_number.label }} {{form.house_number(class="form-control", placeholder="House Number")}}
        </div>
        <div class="col-auto">
          {{ form.city.label }} {{form.city(class="form-control", placeholder="City")}}
        </div>
        <div class="col-auto">
          {{ form.state.label }} {{form.state(class="form-control", placeholder="State")}}
        </div>
        <div class="col-auto">
          {{ form.zip_code.label }} {{form.zip_code(class="form-control", placeholder="Zip Code")}}
        </div>
      </div>
      <br></br>
      {{ form.submit(class="btn btn-primary") }} 
    </form>
  </div>
  {% if submitted %}
    <h3>Client submitted!</h3>
  {%endif%}
        

</div>
{% endblock %}

Land_of_Lakes/templates/client_table.html
{% extends "view_tables.html" %}
{% block content %}
<h1>Client Table:</h1>
<table class="table">
    <tr>
        <th>ID</th>
        <th>SSN</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
    </tr>
    {% for client in client_table %}
    <tr>
        <td>{{client.client_id}}</td>
        <td>{{client.ssn}}</th>
        <td>{{client.first_name}}</th>
        <td>{{client.last_name}}</td>
        <td>{{client.email}}</th>
        <td>{{client.address_id.city}}</td>
        <td>{{client.address_id.state}}</td>
        <td>{{client.address_id.zip_code}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

Land_of_Lakes/templates/connect_advisor.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Connect Advisor</h1>

  <p>This form will connect an advisor with a client using their respective IDs.
     Don't know the client ID? Look it up <a href="{{ url_for('main.search_database') }}">here!</a>
     You can also view all the Advisors and their IDs by 
     <a href="{{ url_for('main.view_tables') }}">viewing their table.</a>
  </p>

  <form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-row">
      <div class="col-auto">
        {{ form.client_id.label }} {{form.client_id}} 
      </div>
    </div>
    <div class="form-row">
      <div class="col">
        {{ form.advisor_id.label }} {{form.advisor_id}} 
      </div>
    </div>
    {{ form.submit(class="btn btn-primary") }}
  </form>

</div>

{% endblock %}

Land_of_Lakes/templates/delete_account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Delete Account</h1>

  <div>
        <p>
                Enter an account number to delete an account. 
                This will not delete any associated Clients.
                You can look up its ID by 
                <a href="{{ url_for('main.view_tables') }}">viewing their table.</a>
        </p>
  </div>

  <div class='form-group'>
    <form method="POST">
      {{ form.hidden_tag() }}
      {{ form.id.label }} {{form.id}}
      {{ form.submit(class="btn btn-primary") }} 
    </form>
  </div>
  {%if account_exists == True %}
     <h3>Account Deleted! </h3>
  {%elif account_exists == False %}
    <h3>Account Doesn't exist! Try again. </h3>  
  {%elif account_exists == None %}
  {% endif %}  
</div>
{% endblock %}

Land_of_Lakes/templates/update_client.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Update Client</h1>

  <p>You can nullify the many to one relationship between clients and addresses
  here. No matter what you choose, this form will also update all fields for
  the client passed in with their ID. Don't know their ID? Look it up
  <a href="{{ url_for('main.search_database') }}">here!</a> </p>

  <div class='form-group'>
    <form method="POST">
      {{ make_null_form.hidden_tag() }}
      {{ make_null_form.make_null.label }} {{make_null_form.make_null(class="btn btn-outline-info dropdown-toggle")}}
      {{ make_null_form.submit(class="btn btn-primary") }}
    </form>
  </div>

  {% if make_null == 'False' %}
    <div class='form-group'>
      <form method="POST" action="">
        {{ update_client_address_form.hidden_tag() }}
        <div class="form-row">
          <div class="col-auto">
            {{ update_client_address_form.id.label }} {{update_client_address_form.id(class="form-control", placeholder="ID")}}
          </div>
          <div class="col-auto">
            {{ update_client_address_form.ssn.label }} {{update_client_address_form.ssn(class="form-control", placeholder="Social Security Number")}}
          </div>
          <div class="col-auto">
            {{ update_client_address_form.email.label }} {{update_client_address_form.email(class="form-control", placeholder="Email")}}
          </div>
        </div>
        <br></br>
        <div class="form-row">
          <div class="col-auto">
            {{ update_client_address_form.first_name.label }} {{update_client_address_form.first_name(class="form-control", placeholder="First Name")}}
          </div>
          <div class="col-auto">
            {{ update_client_address_form.last_name.label }} {{update_client_address_form.last_name(class="form-control", placeholder="Last Name")}}
          </div>
        </div>
        <br></br>
        <div class="form-row">
          <div class="col-auto">
            {{ update_client_address_form.house_number.label }} {{update_client_address_form.house_number(class="form-control", placeholder="House Number")}}
          </div>
          <div class="col-auto">
            {{ update_client_address_form.city.label }} {{update_client_address_form.city(class="form-control", placeholder="City")}}
          </div>
          <div class="col-auto">
            {{ update_client_address_form.state.label }} {{update_client_address_form.state(class="form-control", placeholder="State")}}
          </div>
          <div class="col-auto">
            {{ update_client_address_form.zip_code.label }} {{update_client_address_form.zip_code(class="form-control", placeholder="Zip Code")}}
          </div>
        </div>
        <br></br>
        {{ update_client_address_form.submit(class="btn btn-primary") }}
      </form>

  {%  elif make_null == 'True' %}
    <div class='form-group'>
      <form method="POST" action="">
        {{ update_client_only_form.hidden_tag() }}
        <div class="form-row">
          <div class="col-auto">
            {{ update_client_only_form.id.label }} {{update_client_only_form.id(class="form-control", placeholder="ID")}}
          </div>
          <div class="col-auto">
            {{ update_client_only_form.ssn.label }} {{update_client_only_form.ssn(class="form-control", placeholder="Social Security Number")}}
          </div>
          <div class="col-auto">
            {{ update_client_only_form.email.label }} {{update_client_only_form.email(class="form-control", placeholder="Email")}}
          </div>
        </div>
        <br></br>
        <div class="form-row">
          <div class="col-auto">
            {{ update_client_only_form.first_name.label }} {{update_client_only_form.first_name(class="form-control", placeholder="First Name")}}
          </div>
          <div class="col-auto">
            {{ update_client_only_form.last_name.label }} {{update_client_only_form.last_name(class="form-control", placeholder="Last Name")}}
          </div>
        </div>
        {{ update_client_only_form.submit(class="btn btn-primary") }}
      </form>
  {% endif %}
  </div>
</div>

{% if msg %}
<p>{% print(msg) %}</p>
{% endif %}

{% endblock %}

Land_of_Lakes/templates/view_clients.html
{% extends "view_tables.html" %}
{% block content %}

<table class='table table-striped table-sm'>
    <thead class='thead-light'>
        <th>Client ID</th>
        <th>Social Security Number</th>
        <th>Client Name</th>
        <th>Email</th>
        <th>Address_ID</th>
        <th>Update</th>
    </thead>
    <tbody>

      {% for r in rows %}

      <tr>
        <td> {{ r[0] }}</td>
        <td> {{ r[1] }}</td>
        <td> {{ r[2] }}</td>
        <td> {{ r[3] }}</td>
        <td> {{ r[4] }}</td>
        <td> <input type='button' name='Update' value='Update' class="btn btn-secondary" onclick="window.location = '{{ url_for('add.update_client') }}'"> </td>
      </tr>

      {% endfor %}

    </tbody>

{% endblock %}

Land_of_Lakes/templates/view_tables.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Land Of Lakes Bank</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand nav-link" href=" {{ url_for('main.index') }}">Land of Lakes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbar">
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href=" {{ url_for('add.add_client') }}">Add Client</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('add.add_advisor') }} ">Add Financial Advisor</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('add.add_account') }}">Add Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('add.update_client') }}">Update Client</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('add.delete_account') }}">Delete Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.connect_advisor') }}">Connect Advisor</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.search_database') }} ">Search Database</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.view_tables') }}">View Tables</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="jumbotron">
      <h1>View Tables</h1>

        <p>Clieck on the table wanted below and hit submit to view.</p> 

        <div class="form-group">
          <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-row">
              <div class="col-auto">
                {{ form.tables.label }} {{form.tables(class="btn btn-outline-info dropdown-toggle")}} 
                {{ form.submit(class="btn btn-primary") }} 
              </div>
            </div>
          </form>
        </div>
    </div>
    {% block content %}
    
    {% endblock %}
  </body>
</html>